import 'package:flutter_application_terra_link_test/functions/builders/common_requisites_of_watching_task_page_builder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/file_display_builder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/multiple_file_display_builder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/profile_block_builder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/requisites_page_builder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/single_file_display_builder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/task_block_bulilder.dart';
import 'package:flutter_application_terra_link_test/functions/builders/task_counter_block_builder.dart';
import 'package:flutter_application_terra_link_test/functions/checkers/future_builder_checker.dart';
import 'package:flutter_application_terra_link_test/functions/generators/generate_docs_block_list.dart';
import 'package:flutter_application_terra_link_test/functions/generators/generate_task_block_list.dart';
import 'package:flutter_application_terra_link_test/functions/getters/common_requisites_getter.dart';
import 'package:flutter_application_terra_link_test/functions/getters/get_files.dart';
import 'package:flutter_application_terra_link_test/functions/getters/get_json_profile_list.dart';
import 'package:flutter_application_terra_link_test/functions/getters/get_json_orders_list.dart';
import 'package:flutter_application_terra_link_test/functions/getters/get_json_tasks_list.dart';
import 'package:flutter_application_terra_link_test/functions/getters/task_watch_section_pages_getter.dart';
import 'package:flutter_application_terra_link_test/functions/getters/task_watch_sections_pages_list_get.dart';
import 'package:flutter_application_terra_link_test/functions/processors/success_auth_request_future_builder_processor.dart';
import 'package:flutter_application_terra_link_test/functions/processors/success_docs_request_future_builder_processor.dart';
import 'package:flutter_application_terra_link_test/functions/processors/success_tasks_request_future_builder_processor.dart';
import 'package:flutter_application_terra_link_test/functions/requests/get_data_about_route_tasks.dart';
import 'package:flutter_application_terra_link_test/functions/requests/get_doc_content_request.dart';
import 'package:flutter_application_terra_link_test/functions/requests/get_info_rk_atributes.dart';
import 'package:flutter_application_terra_link_test/functions/requests/get_list_of_rk_attachments.dart';
import 'package:flutter_application_terra_link_test/functions/requests/order_list_get_function.dart';
import 'package:flutter_application_terra_link_test/functions/requests/profile_get_function.dart';
import '../functions/requests/auth_ticket_get_function.dart';
import '../functions/requests/task_list_get_function.dart';
import '../functions/processors/bad_response_preprocor.dart';
import '../functions/processors/respones_code_processor.dart';
import '../functions/processors/get_task_list_processor.dart';
import 'package:flutter_application_terra_link_test/functions/get_pass.dart';

final funConatiner = <String, Function>{
  'getKeyAuth': authTicketGetFunction,
  'getTaskList': taskListGetFunction,
  'stdBadResponsePreprocessor': stdBadResponsePreprocessingFunction,
  'responesCodeProcessor': responesCodeProcessor,
  'getTaskListProcessor': getTaskListProcessor,
  'getPass': getPass,
  'taskCountersContainerBuilder': taskCountersContainerBuilder,
  'taskBlockBuilder': taskBlockBuilder,
  'getJsonTasksList': getJsonTasksList,
  'generateTaskBlockList': generateTaskBlockList,
  'futureBuilderChecker': futureBuilderChecker,
  'successTasksRequestFutureBuilderProcessor': successTasksRequestFutureBuilderProcessor,
  'successDocsRequestFutureBuilderProcessor': successDocsRequestFutureBuilderProcessor,
  'orderListGetFunction': orderListGetFunction,
  'getJsonOrdersList': getJsonOrdersList,
  'getJsonProfileMap': getJsonProfileMap,
  'profileListGetFunction': profileListGetFunction,
  'successAuthRequestFutureBuilderProcessor': successAuthRequestFutureBuilderProcessor,
  'profileBlockBuilder': profileBlockBuilder,
  'generateDocsBlockList': generateDocsBlockList,
  'docsCountersContainerBuilder': taskCountersContainerBuilder,
  'filesListOfWatchingTaskGetter': getFilesListOfWatchingTask,
  'requisitesPageBuilder': requisitesPageBuilder,
  'taskWatchSectionsPagessListGetter': taskWatchSectionsPagessListGetter,
  'requisitesPageParamsGetter': commonRequisitesOfWatchingTaskGetter,
  'getInfoRKAtributes': getInfoRKAtributes,
  'commonRequisites': getInfoRKAtributes,
  'getFile': getFilesListOfWatchingTask,
  'fileDisplayBuilder': fileDisplayBuilder,
  'taskWatchSectionPagesGetter':  taskWatchSectionPagesGetter,
  'commonRequisitesOfWatchingTaskGetter': commonRequisitesOfWatchingTaskGetter,
  'commonRequisitesOfWatchingTaskPageBuilder': commonRequisitesOfWatchingTaskPageBuilder,
  'getDataAboutRouteOFWatchingTask': getDataAboutRouteTask,
  'getListOfRKAttachments': getListOfRKAttachments,
  'getFilesListOfWatchingTask': getFilesListOfWatchingTask,
  'getDocContent': getDocContent,
  'singleFileDisplayBuilder': singleFileDisplayBuilder,
  'multipleFileDisplayBuilder': multipleFileDisplayBuilder
};